name: Node CI

on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      on: push

    #  - uses: secrethub/actions/env-export@v0.1.0
    #     env:
    #       SECRETHUB_CREDENTIAL: ${{ secrets.ENV_ID }}
    #       SLACK_WEBHOOK: secrethub://company/app/slack/webhook
      - name: Print environment with masked secrets
        run: printenv
      # - name: Deploy(Upload COS)
      #   uses: zkqiang/tencent-cos-action@v0.1.0
      #   with:
      #     args: delete -f -r / && upload -r ./public/ /
      #     secret_id: ${{ secrets.SECRET_ID }}
      #     secret_key: ${{ secrets.SECRET_KEY }}
      #     bucket: ${{ secrets.BUCKET }}
      #     region: ${{ secrets.REGION }}

      # - name: Deploy static to Tencent CloudBase
      #   id: deployStatic
      #   uses: TencentCloudBase/cloudbase-action@v1.1.1
      #   with:
      #     secretId: ${{ secrets.SECRET_ID }}
      #     secretKey: ${{ secrets.SECRET_KEY }}
      #     envId: ${{ secrets.ENV_ID }}
      #     staticSrcPath: public
